### ISSUE TITLE
Could not render map using renderer me.matsubara.miphone.phone.Phone : StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ClayCoffee** [aematsubara/MiPhone#2]
[17:42:44 ERROR]: Could not render map using renderer me.matsubara.miphone.phone.Phone
java.lang.StringIndexOutOfBoundsException: begin -1, end 10, length 10
        at java.lang.String.checkBoundsBeginEnd(String.java:4608) ~[?:?]
        at java.lang.String.substring(String.java:2711) ~[?:?]
        at me.matsubara.miphone.phone.render.TextDraw.handleRender(TextDraw.java:81) ~[miphone-1.1.1.jar:?]
        at me.matsubara.miphone.phone.Phone.handleRenders(Phone.java:1010) ~[miphone-1.1.1.jar:?]
        at me.matsubara.miphone.phone.Phone.render(Phone.java:770) ~[miphone-1.1.1.jar:?]
        at org.bukkit.craftbukkit.v1_20_R2.map.CraftMapView.render(CraftMapView.java:164) ~[purpur-1.20.2.jar:git-Purpur-"4f43c72"]
        at net.minecraft.world.level.saveddata.maps.MapItemSavedData$HoldingPlayer.nextUpdatePacket(MapItemSavedData.java:635) ~[?:?]
        at net.minecraft.world.level.saveddata.maps.MapItemSavedData.getUpdatePacket(MapItemSavedData.java:439) ~[?:?]
        at net.minecraft.world.item.MapItem.getUpdatePacket(MapItem.java:350) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:789) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:351) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:601) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:240) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1607) ~[purpur-1.20.2.jar:git-Purpur-"4f43c72"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.2.jar:git-Purpur-"4f43c72"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[purpur-1.20.2.jar:git-Purpur-"4f43c72"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[purpur-1.20.2.jar:git-Purpur-"4f43c72"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[purpur-1.20.2.jar:git-Purpur-"4f43c72"]
        at java.lang.Thread.run(Thread.java:842) ~[?:?]

**Comment by ClayCoffee** [comment]
it only supports 2 pages
